name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Defina a versão do Node.js para 16

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Copy from master to main
        run: |
          git checkout master
          git pull
          git checkout main
          git merge master
          git push
